### ISSUE TITLE
network structure bugs

### ISSUE THREAD

**Issue by tacchan7412** [crcrpar/pytorch.sngan_projection#17]
I found some differences in the networks from https://github.com/pfnet-research/sngan_projection . Please check below.

## pytorch.sngan_projection/models/discriminators/snresnet.py  

https://github.com/crcrpar/pytorch.sngan_projection/blob/f57f5f794a5ceeae855618d1552794baa18932c9/models/discriminators/snresnet.py#L29
->
```
activation=activation, downsample=False)
```

## pytorch.sngan_projection/models/discriminators/resblocks.py
 
https://github.com/crcrpar/pytorch.sngan_projection/blob/f57f5f794a5ceeae855618d1552794baa18932c9/models/discriminators/resblocks.py#L21
-> 
```
h_ch = in_ch
```

https://github.com/crcrpar/pytorch.sngan_projection/blob/f57f5f794a5ceeae855618d1552794baa18932c9/models/discriminators/resblocks.py#L26
->
```
self.c_sc = utils.spectral_norm(nn.Conv2d(in_ch, out_ch, 1, 1, 0))
```

https://github.com/crcrpar/pytorch.sngan_projection/blob/f57f5f794a5ceeae855618d1552794baa18932c9/models/discriminators/resblocks.py#L43
-> 
```
return F.avg_pool2d(x, 2)
```

## pytorch.sngan_projection/models/generators/resnet.py

https://github.com/crcrpar/pytorch.sngan_projection/blob/f57f5f794a5ceeae855618d1552794baa18932c9/models/generators/resnet.py#L40
->
```
self.conv7 = nn.Conv2d(num_features, 3, 3, 1, 1)
```

**Comment by crcrpar** [comment]
Really appreciate this reporting!

**Comment by crcrpar** [comment]
@tacchan7412 I'll check the block definitions ASAP though I'll just add to README comments about snresnet.py & resnet.py instead of fixing them because I don't have any plan to experiment on 128x128 images.
I really apologize for these bugs and bothering you and appreciate this comparison!
