### ISSUE TITLE
utils.py line 68 

### ISSUE THREAD

**Issue by KiBeomHong** [crcrpar/pytorch.sngan_projection#20]
Hello

May i have one question?

utils.py > line 68~69
if distribution is None:
    distribution == 'normal' -> I think it maybe " distribution = 'normal' "

if i'm wrong, please tell me what means == 

Thanks for your nice code :)

**Comment by crcrpar** [comment]
Hi @KiBeomHong 

Sorry for late reply.

You are absolutely right!
It must be 
```python
if distribution is None:
    distribution = 'normal'
```
.

I didn't notice because I set args.gen_distribution that was passed to sample_z function as distribution argument by default.

~Thank you I 'll fix it in #19~
I'll fix it in a separate pull.
